"""FinBrain Python SDK."""
from __future__ import annotations

try:
    # Generated by setuptools-scm during any pip install (including -e)
    from ._version import version as __version__          # type: ignore
except ModuleNotFoundError:
    # Running from a fresh Git checkout → ask metadata
    from importlib.metadata import PackageNotFoundError, version as _v

    try:
        __version__ = _v("finbrain-python")               # dist name
    except PackageNotFoundError:
        __version__ = "0.0.0.dev0"

from .client import FinBrainClient

__all__ = ["FinBrainClient", "__version__"]
